name: Trigger auto deployment for chuotcord-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/chuotcord-app-AutoDeployTrigger-f335fbf8-5d0f-43ae-9a01-e454888e5546.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CHUOTCORDAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CHUOTCORDAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CHUOTCORDAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.CHUOTCORDAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CHUOTCORDAPP_REGISTRY_PASSWORD }}
          containerAppName: chuotcord-app
          resourceGroup: chuotcord
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


