name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-push-image:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Upload docker-compose.yml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compose-file
          path: docker-compose.yml

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Compose (v1.29.2)
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-push-image

    steps:
      - name: Download compose file
        uses: actions/download-artifact@v4
        with:
          name: compose-file
          path: ./

      - name: Prepare SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Copy compose file to remote
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          scp -i private_key docker-compose.yml $SSH_USERNAME@$SSH_HOST:~/docker-compose.yml
          ssh -i private_key $SSH_USERNAME@$SSH_HOST "sudo mv ~/docker-compose.yml /ChuotCordV2/docker-compose.yml && sudo chown root:root /ChuotCordV2/docker-compose.yml"

      - name: Pull images and restart on remote
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          ssh -i private_key $SSH_USERNAME@$SSH_HOST << 'EOF'
            sudo -s
            cd /ChuotCordV2 || exit 1
            export NODE_ENV=${{ secrets.NODE_ENV }}
            export PORT=${{ secrets.PORT }}
            export MONGODB_URL=${{ secrets.MONGODB_URL }}
            export REDIS_HOST=${{ secrets.REDIS_HOST }}
            export REDIS_PORT=${{ secrets.REDIS_PORT }}
            export REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            export JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}
            export JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
            export JWT_RECOVERY_SECRET=${{ secrets.JWT_RECOVERY_SECRET }}
            export JWT_ACCESS_EXPIRATION_MINUTES=${{ secrets.JWT_ACCESS_EXPIRATION_MINUTES }}
            export JWT_REFRESH_EXPIRATION_DAYS=${{ secrets.JWT_REFRESH_EXPIRATION_DAYS }}
            export JWT_RESET_PASSWORD_EXPIRATION_MINUTES=${{ secrets.JWT_RESET_PASSWORD_EXPIRATION_MINUTES }}
            export JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=${{ secrets.JWT_VERIFY_EMAIL_EXPIRATION_MINUTES }}
            export RTC_MIN_PORT=${{ secrets.RTC_MIN_PORT }}
            export RTC_MAX_PORT=${{ secrets.RTC_MAX_PORT }}
            export RTC_ANNOUNCED_IP=${{ secrets.RTC_ANNOUNCED_IP }}
            export SMTP_HOST=${{ secrets.SMTP_HOST }}
            export SMTP_PORT=${{ secrets.SMTP_PORT }}
            export SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
            export SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
            export EMAIL_FROM=${{ secrets.EMAIL_FROM }}
            export SERVER_HOST=${{ secrets.SERVER_HOST }}
            export CLIENT_HOST=${{ secrets.CLIENT_HOST }}
            export SSL_CERT_PATH=${{ secrets.SSL_CERT_PATH }}
            export SSL_KEY_PATH=${{ secrets.SSL_KEY_PATH }}
            export UPLOADS_DIR=${{ secrets.UPLOADS_DIR }}
            export CORS_ORIGIN_DEVELOPMENT=${{ secrets.CORS_ORIGIN_DEVELOPMENT }}
            export CORS_ORIGIN_PRODUCTION=${{ secrets.CORS_ORIGIN_PRODUCTION }}
            export USE_HTTPS=${{ secrets.USE_HTTPS }}
            export HTTPS=${{ secrets.HTTPS }}
            export REACT_APP_CLIENT_HOST=${{ secrets.REACT_APP_CLIENT_HOST }}
            export REACT_APP_CHAT_SERVER_HOST=${{ secrets.REACT_APP_CHAT_SERVER_HOST }}
            export REACT_APP_CMS_SERVER_HOST=${{ secrets.REACT_APP_CMS_SERVER_HOST }}
            export REACT_APP_CHAT_SERVER_API_URL=${{ secrets.REACT_APP_CHAT_SERVER_API_URL }}
            docker compose pull
            docker compose up -d
            echo "completed"
          EOF